name: Lab Test
# Will be triggered when I push to my private repo
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Private Source Repository
        # Get the private source code from the private repository.
        uses: actions/checkout@v3
        with:
          repository: endless-hu/CMU-bustub
          token: ${{ secrets.GH_PAT }}
          path: priv_repo

      - name: Checkout This Repo
        uses: actions/checkout@v3
        with:
          path: this_repo

      - name: Setup Build Environment
        run: sudo bash priv_repo/build_support/packages.sh -y

      - name: Build the Project
        run: |
          cd priv_repo
          mkdir build
          cd build
          cmake ..
          make -j 2
          make build-tests -j 2

      - name: Run All Unit Tests
        run: |
          cd priv_repo/build
          timeout 2m make check-tests -j 2
          cd ..
          # copy test source code to this repo
          rm -rf ../this_repo/test
          cp -r test ../this_repo/test/
          # copy commit histroy to this repo
          git log > ../this_repo/src_commit_history.txt

      - name: Update /test
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Zhijing Hu
          author_email: qq906555703@gmail.com
          cwd: ./this_repo/
          message: "Update /test"
          
